"""add progress_snapshots table

Revision ID: 2ac157e83da1
Revises: 0394621edd2a
Create Date: 2026-09-07 12:28:51.634790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ac157e83da1'
down_revision: Union[str, Sequence[str], None] = '0394621edd2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progress_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('hydration', sa.Float(), nullable=True),
    sa.Column('oiliness', sa.Float(), nullable=True),
    sa.Column('texture', sa.Float(), nullable=True),
    sa.Column('redness', sa.Float(), nullable=True),
    sa.Column('pigmentation', sa.Float(), nullable=True),
    sa.Column('blemish_index', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progress_snapshots')
    # ### end Alembic commands ###
