"""add products, ingredients, and interaction tables

Revision ID: 56f022349ec1
Revises: 629d6953da70
Create Date: 2026-09-06 22:51:42.265549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56f022349ec1'
down_revision: Union[str, Sequence[str], None] = '629d6953da70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('inci_name', sa.String(), nullable=True),
    sa.Column('function', sa.String(), nullable=True),
    sa.Column('concern_tags', sa.ARRAY(sa.String()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('shopify_product_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('routine_step', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('product_url', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('shopify_product_id')
    )
    op.create_table('ingredient_interactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_a_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_b_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('synergistic', 'caution', 'avoid_same_routine', name='ingredientinteractiontype'), nullable=False),
    sa.Column('explanation', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_a_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['ingredient_b_id'], ['ingredients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_ingredients',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('concentration_note', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('product_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_ingredients')
    op.drop_table('ingredient_interactions')
    op.drop_table('products')
    op.drop_table('ingredients')
    # ### end Alembic commands ###
